### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by ton1517** [ryutamaki/Circle#1]
I can't build this project :cry: 
please tell me how to build.

**Comment by ryutamaki** [comment]
You must link cocos2dx source code and install cocos studios to create binary files.
It gets complex and I don't make sure what the correct ways are, so I'll upload to DeployGate in this week. plz wait to be invited.

**Comment by ton1517** [comment]
@ryutamaki 
ok! I'm looking forward to playing your game :exclamation: :laughing: :exclamation:

**Comment by ryutamaki** [comment]
Here is a download link.
https://dply.me/mtrf55
